### PR TITLE
Runtime errors and multiple assertions

### LINKED ISSUE #41: Errors in tests are not reported
If any unexpected runtime errors is thrown while executing a test, it is not being reported correctly right now. There are two scenarios:

1. If the test only has one assertion, then the test is reported as failed but with no message.

This makes it hard to figure out what went wrong. In Clojure it's quite easy (especially as a learner) to have some accidental runtime errors e.g. passing an odd number of forms to `(cond)` because they forgot to put `:else` before the last form. Whenever this happened to me I would have to copy paste my whole code into a clojure repl on my machine and then try running the code from the tests to see the error.

To reproduce this, use the following code in the Hello World exercise:

```clojure
(ns hello-world)

(defn hello []
  (assert false))
```

2. If the test has multiple assertions and one or more of them throws an exception, then:
   1. the test is reported as passed if *any* of the other assertions pass, or failed (without message like in the first scenario) if all either failed or errored.
   2. Even if it is reported as passed, the overall status is still failed
   3. If it is reported as passed, it won't increase the overall test failure count.

So the user will often see "0 tests failed" in red, and all tests show green, but then they can't submit and are told to first make all tests pass.

To reproduce this, use this solution for the Go Counting exercise (designed to pass the at least one assertion of each test but throw exceptions for some other assertions):

```clojure
(ns go-counting)

;; passes the last 4 assertions, throws on the first 4
(defn territory [grid [x y]]
  (assert false)) 

;; passes the first assertion, throws on the others
(defn territories [grid]
  (assert (= grid [" "]))
  {:black-territory #{} :white-territory #{} :null-territory  #{[0 0]}})
```

I believe the cause for both issues is a combination of the following things in `test-runner.clj`
1. [line 84](https://github.com/exercism/clojure-test-runner/blob/main/test-runner.clj#L84) - unlike for pass and fail, in case of errors only the name is saved and not the message. Not sure if we want to use the `:message` directly from clojure.test or craft our own? It might be helpful to include the line number as well (clojure.test provides this with key `:line`)
2. unlike pass/fail, the errors atom just stores a vector of strings instead of a vector of maps, but on [line 106](https://github.com/exercism/clojure-test-runner/blob/main/test-runner.clj#L106) it is being treated as a map (trying to access the `:name` key). This would be fixed by changing line 84 to use a map, but we must be careful to update line 104 as well to be like the fail/pass cases.
3. It seems that when a test has multiple assertions, clojure.test calls `report` multiple times, once for each assertion, which means that the same test name will appear in more than one of the test results atoms. This is a bigger issue that maybe should have its own ticket, because if some assertions pass and others fail the test is shown is passing but the overall result is fail.

### PR DESCRIPTION
**Pull request by miridius**
Closes #41
Closes exercism/clojure#420
Closes exercism/clojure#421

I made the following updates:

1. Tests which throw an error now include a message informing the user of the error
2. Tests which have multiple assertions will fail/error if any of the assertions fails or errors
3. Test code for multiple assertion tests (previously only showed the first assertion) will now show either
   - the first failing/erroring assertion in case there is one
   - all assertions if they all pass

I added tests for all of the above, which are passing along with all the existing tests.

I also made a few QOL changes:
- run-tests.sh now reports failures and overall status
- run-tests.sh now uses jq for diffing the results files, so that formatting is ignored and pretty printing is not needed
- updated README with the correct testing command
- refactored test-runner.clj a bit to make it clearer & more efficient.

### CODE REVIEW

**Comment by BTowersCoding** [comment]
This is amazing! The assertion counter elegantly solves the first major issue we had with the nested assertions. I went wild in #22 trying to handle everything before realizing, as you confirmed, was a fun exercise but not necessary. I never actually solved the problem though, merely avoided it with https://github.com/exercism/clojure/pull/422 by simply getting rid of all of the nested assertions. Apparently I missed the ones in `go-counting`. I wonder if there are any others... anyway, thanks for doing this! I also love the way you cleaned up the reporting logic, it's a huge improvement.

In addition to confirming the tests pass in this repo's CI, I also verified that all of the practice and concept exercise unit tests in the track itself still pass with their example solutions. I don't believe I have approval privileges here but I'll let the admin team know this is safe to merge.

**Review by BTowersCoding — APPROVED** [review]

**Comment by miridius** [comment]
Awesome I'm glad you like it!

I only read #22 after making this, and it didn't occur to me until then that the multiple assertions might be nested, I had just unconsciously assumed they'd be a flat list under the `deftest`. I think before merging this PR we need to handle the nested cases as well or at least make sure to fail gracefully, since this change as it is will try to access the assertions array out of bounds and I'm not sure what will happen. Properly handling them might be better to go in a separate PR? I'm not sure.

> Or rather, thought I did - apparently I missed the ones in go-counting. I wonder if there are any others...

I've just checked via a grep in the exercism/clojure repo, and found some in these files:

- `exercises/concept/date-parser/test/date_parser_test.clj` - I think this exercise isn't published yet?
- `exercises/practice/hexadecimal/test/hexadecimal_test.clj` - would be fixed by this PR
- `exercises/practice/bank-account/test/bank_account_test.clj` - this one is nested so this PR currently won't fix it
- `exercises/practice/largest-series-product/test/largest_series_product_test.clj` - would by fixed by this PR, though each assertion is inside a `testing`
- `exercises/practice/queen-attack/test/queen_attack_test.clj` - would be fixed
- `exercises/practice/hamming/test/hamming_test.clj` - would be fixed
- `exercises/practice/go-counting/test/go_counting_test.clj` - would be fixed
- `exercises/practice/isogram/test/isogram_test.clj` - would be fixed
- `exercises/practice/kindergarten-garden/test/kindergarten_garden_test.clj` - multiple assertions in a let, would not be fixed
- `exercises/practice/clock/test/clock_test.clj` - would be fixed, though each is inside a larger form
- `exercises/practice/binary-search-tree/test/binary_search_tree_test.clj` - multiple assertions in a let, would not be fixed

This next list of test files only have a single assertion per test, but it's inside a testing form like `(testing "foo" (is ...))` which means that whole form gets reported as the test_code. Which is actually kind of helpful to the user to be honest... so maybe we want to keep it that way?

- `exercises/concept/bird-watcher/test/bird_watcher_test.clj`
- `exercises/concept/cars-assemble/test/cars_assemble_test.clj`
- `exercises/concept/annalyns-infiltration/test/annalyns_infiltration_test.clj`
- `exercises/practice/all-your-base/test/all_your_base_test.clj`
- `exercises/practice/armstrong-numbers/test/armstrong_numbers_test.clj`
- `exercises/practice/run-length-encoding/test/run_length_encoding_test.clj`
- `exercises/practice/complex-numbers/test/complex_numbers_test.clj`
- `exercises/practice/octal/test/octal_test.clj`
- `exercises/practice/robot-simulator/test/robot_simulator_test.clj` - inside a let rather than a testing, which means it's actually really good that the whole form is reported
- `exercises/practice/robot-name/test/robot_name_test.clj` - also inside a let
- `exercises/practice/trinary/test/trinary_test.clj`
- `exercises/practice/secret-handshake/test/secret_handshake_test.clj`
- `exercises/practice/atbash-cipher/test/atbash_cipher_test.clj` - inside a let
- `exercises/practice/pascals-triangle/test/pascals_triangle_test.clj`
- `exercises/practice/collatz-conjecture/test/collatz_conjecture_test.clj`
- `exercises/practice/flatten-array/test/flatten_array_test.clj`
- `exercises/practice/perfect-numbers/test/perfect_numbers_test.clj`
- `exercises/practice/spiral-matrix/test/spiral_matrix_test.clj`

As a first step I think we should pick a good cross section of examples from all of the above and add them as tests to make sure this PR isn't breaking something. As a next step we should think about how to report on assertions that are inside a `let` or a `testing` clause... we can have a look how other test runners do it but my first thought is that we could include the "context path" but not the other assertions, so for example if we have something like:
```clojure
(deftest a-test
  (testing "foo"
    (let [result (my-fn input)]
      (is (= 10 (count result)))
      (is (= :foo (first result)))
      (is ...
```
then if the second assertion fails, the test code would be reported as `(testing "foo" (let [result (my-fn input)] (is (= :foo (first result)))))`

>  I also verified that all of the practice and concept exercise unit tests in the track itself still pass with their example solutions using this updated test-runner.clj

Oh cool I wanted to do something similar but I wasn't sure how! How do you do that? Maybe we should copy them all into this repo's tests folder (with a bash script to sync changes in future) so that we make sure that we always test them?

**Comment by miridius** [comment]
Converting for draft to prevent merging for now until we add more tests

**Comment by miridius** [comment]
Ok so I did as I suggested and added some tests for the different types of nesting I found in the exercises. Sure enough multiple assertions inside a single form (e.g. `let`) would crash the whole test runner if one of the later ones fails, due to an out of bounds exception. So it's a good thing this PR was not merged as it was!

I think the lesson there is that running the test runner against all the exemplary solutions is great but it's not enough, we should also run test failure scenarios. I think an easy way to do the is test against the boilerplate source in each exercise, that should make all tests fail (or possibly throw arity exceptions when the args are empty?)

Anyway moving on, I decided on a middle ground solution for nested assertions: when an assertion fails, show the whole "top level" form (i.e. the forms that make up the `deftest` body) which contains that assertion. When one passes, show the whole test body. This is not necessarily the best final solution but it is definitely an improvement on what we have today!

**Comment by BTowersCoding** [comment]
Brilliant! I'm learning a lot from playing around with this. Life is crazy at the moment so I'm not able to give it the immediate attention I'd like to, this is just really exciting for me because I've been wanting help with this for many months and wasn't sure who to ask.

About the question regarding the `(z/of-string (z/->string loc))`, when pondering how to clean that up I had somewhat of a light-bulb moment, maybe the answer is to not use zippers at all? How are you liking rewrite-clj's zip API? This project was kind of a breakthrough for me because I was totally confused by zippers until it clicked while writing it. So I was overjoyed that I finally understood them. But then I heard from Michiel Borkent (borkdude) that he doesn't use them in clj-kondo or at all, instead preferring the node API. His opinions tend to be very well reasoned so it might have caused me to realize that zippers can be legitimately unwieldy. I'm tempted to try using the node API instead, though I understand if this seems like an extreme reaction to a rather insignificant code issue.

**Comment by miridius** [comment]
Ok, so for fun (and for better testing of course ;)) I wrote another testing script which runs the current test runner against all the exercises in the Clojure track, in _both_ their unsolved and solved versions. It keeps snapshots checked into git (which you can update by running with -u) of the expected results and compares them. Doing so I found and fixed 2 bugs:

1. If a test threw an ExceptionInfo, the whole stack trace was shown in the report, which is not what we want
2. If a test uses the `are` macro, which expands to multiple `is` forms, the test runner would crash with an out of bounds error when trying to find the assertion for a failed test. I tried to solve this by macro-expanding the `are` forms using the zipper but couldn't get it to work, so instead as a workaround it just reports the whole test body if the index is ever out of bounds for whatever reason, which should solve any other macro shenanigans as well.

> Brilliant! I'm learning a lot from playing around with this.

Me too! It's kind of like a natural extension after finishing all the Clojure exercises, putting those skills into practice 😃 

> Life is crazy at the moment so I'm not able to give it the immediate attention I'd like to, this is just really exciting for me because I've been wanting help with this for many months and wasn't sure who to ask, and now that you've stepped in I wish I could just drop everything and join the party but I'm currently overwhelmed with some personal issues.

No worries! Life comes first :) I'm quite busy myself but I really wanted to get this done before I go on vacation! But then there's always just one more change to make...  

> About the question regarding the `(z/of-string (z/->string loc))`, when pondering how to clean that up I had somewhat of a light-bulb moment, maybe the answer is to not use zippers at all? How are you liking rewrite-clj's zip API? This project was kind of a breakthrough for me because I was totally confused by zippers until it clicked while writing it. So I was overjoyed that I finally understood them and pretty enamored for awhile. But then I heard from Michiel Borkent (borkdude) that he doesn't use them in clj-kondo or at all, instead preferring the [node API](https://cljdoc.org/d/rewrite-clj/rewrite-clj/1.1.45/doc/user-guide#node-api). His opinions tend to be very well reasoned and if he says zippers are confusing then maybe it's not just me. It's incredibly cool how they work though! I'm tempted to try using the node API instead, though I understand if this seems like an extreme reaction to a rather insignificant code issue.
>
> EDIT: Apparently zippers are also slower than working with the rewrite-clj nodes directly. See the [clj-kondo parser](https://github.com/clj-kondo/clj-kondo/blob/master/src/clj_kondo/impl/utils.clj), but be aware that it uses its own fork of `rewrite-clj` which seems to be organized differently... (the original author kind of abandoned it before it was transferred to `clj-commons`.)

I think the zipper is ok for now... I do find it kind of a pain to use and hard to troubleshoot (as eluded to above not being able to solve the `are` problem), and so maybe the node API is better (I haven't tried it) BUT as long as the existing solution is working I wouldn't recommend that we rewrite it. Unless you just want to for fun/learning which is always a great reason... but let's not do that in this PR 😄

I do find it a bit strange that we are parsing the code at all, I wonder if there's a way to solve this using an existing test runner solution... but on the other hand we always need to examine the code at some level to be able to report the individual test code to the UI so I dunno. Let's first try to get these fixes in and then we can think about next steps!

> Oh, and it seems that `z/->string` is deprecated, and the new one is just [`z/string`](https://cljdoc.org/d/rewrite-clj/rewrite-clj/1.1.45/api/rewrite-clj.zip#string).
> 
> EDIT: actually, have you seen [`z/subedit->`](https://cljdoc.org/d/rewrite-clj/rewrite-clj/1.1.45/doc/user-guide#sub-editing)? It seems that might be exactly what you're looking for. Or even [`z/postwalk`](https://cljdoc.org/d/rewrite-clj/rewrite-clj/1.1.45/api/rewrite-clj.zip#postwalk)! Both are specifically meant for the task of traversing an isolated sub-tree.

Ah good to know! I don't think pre/postwalk or subedit will work since they are more for editing the tree and don't really have an escape hatch out of the editing process. But, there is `subzip` instead which does work! I'll make that change now

**Comment by BTowersCoding** [comment]
> Ok, so for fun (and for better testing of course ;)) I wrote another testing script which runs the current test runner against all the exercises in the Clojure track, in both their unsolved and solved versions. It keeps snapshots checked into git (which you can update by running with -u) of the expected results and compares them.

This is incredibly valuable because it could replace the test script we're using in CI which is terribly crude in comparison, and I hadn't even gotten it to a stage where it's a true integration test. I got a bit stuck and had it on my todo list, but this is actually much closer to what I had in mind for how a test runner _should_ be.

**Comment by BTowersCoding** [comment]
> I do find it a bit strange that we are parsing the code at all, I wonder if there's a way to solve this using an existing test runner solution.

Yeah, I think the only reason is because of the requirement that the tests be reported in order, and `clojure.test` fundamentally reports them randomly. I don't think there's a way to change this behavior, but as I recall I simply thought "whatever, I'll just have a script that _looks_ in the test file to get the tests, and check them individually", and that's how the whole zipper thing happened. 

At one point before that, I was using the Kaocha test runner which can optionally do them in order, but since it uses actual JVM Clojure, the startup time was undesirable for the purpose of rapidly checking iterations on the site. That's when I made the decision to use babashka, which is a bit of a compromise because the small differences are responsible for a lot of confusion when people solve the exercises locally using certain Java methods that don't pass when submitted.

**Review by ErikSchierboom — APPROVED** [review]
Awesome job!

**Comment by ErikSchierboom** [comment]
> I don't believe I have approval privileges here but I'll let https://github.com/orgs/exercism/teams/maintainers-admin know this is safe to merge.

You do!

**Pull request merged**
