### PR TITLE
Upgrade to version 3 spec

### LINKED ISSUE #15: Upgrade to version 3 spec
If possible, this test runner should be updated to version 3 of the [test runner interface specification](https://github.com/exercism/docs/blob/main/building/tooling/test-runners/interface.md). In version 3, one additional feature is enabled: the ability to link individual tests to tasks.
This allows the website to show which tests belong to which tasks.

The way tests are linked to tasks is via an (optional) `task_id` field, which is an integer that matches the number of the task as defined in the exercise's `instructions.md` file (note: the instructions start at index 1).

This is an example of a test in the `results.json` file:

```json
{
  "name": "Expected oven time in minutes",
  "status": "pass",
  "task_id": 1,
  "test_code": "Assert.Equal(40, Lasagna.ExpectedMinutesInOven());"
}
```

You are completely free in how to implement this. Some options are:

1. Add metadata to a test that the test runner can then discover while running the tests (e.g. an attribute or annotation)
2. Define a test name/task id mapping (e.g. in the exercise's `.meta/config.json` file)
3. Any other option you can think of...

As this test runner currently implements version 1 of the test runner specification, it might be good to first upgrade to version 2 of the test runner specification before upgrading to version 3.

Let me know if there are any questions.

### PR DESCRIPTION
**Pull request by miridius**
Closes #15

**NOTE: This PR depends on #42, that PR must be merged before this one!**

This PR adds support for specifying the task ID on tests using metadata, which will then be reported in the results.json.

For example:

```clojure
(deftest ^{:task 1} list-empty-test
  (is (= '() (tracks-on-tracks-on-tracks/new-list))))

(deftest ^{:task 2} list-add-test
  (is (= '("JavaScript" "Java" "Lisp" "Clojure")
         (-> (tracks-on-tracks-on-tracks/new-list)
             (tracks-on-tracks-on-tracks/add-language "Clojure")
             (tracks-on-tracks-on-tracks/add-language "Lisp")
             (tracks-on-tracks-on-tracks/add-language "Java")
             (tracks-on-tracks-on-tracks/add-language "JavaScript")))))

(deftest ^{:task 3} first-test
  (is (= "Lisp" (tracks-on-tracks-on-tracks/first-language '("Lisp" "Clojure")))))

(deftest ^{:task 4} list-remove-test
  (is (= '("Clojure") (tracks-on-tracks-on-tracks/remove-language '("Lisp" "Clojure")))))

(deftest ^{:task 5} list-count-test
  (is (= 3 (tracks-on-tracks-on-tracks/count-languages '("JavaScript" "Java" "Clojure")))))

(deftest ^{:task 6} learning-list-test
  (is (= 3 (tracks-on-tracks-on-tracks/learning-list))))
```

Will produce output like this:
```json
{
  "version": 3,
  "status": "fail",
  "tests": [
    {
      "name": "list-empty-test",
      "status": "pass",
      "task_id": 1,
      "test_code": "(is (= (quote ()) (tracks-on-tracks-on-tracks/new-list)))"
    },
    {
      "name": "list-add-test",
      "status": "pass",
      "task_id": 2,
      "test_code": "(is (= (quote (\"JavaScript\" \"Java\" \"Lisp\" \"Clojure\")) (-> (tracks-on-tracks-on-tracks/new-list) (tracks-on-tracks-on-tracks/add-language \"Clojure\") (tracks-on-tracks-on-tracks/add-language \"Lisp\") (tracks-on-tracks-on-tracks/add-language \"Java\") (tracks-on-tracks-on-tracks/add-language \"JavaScript\"))))"
    },
    {
      "name": "first-test",
      "status": "pass",
      "task_id": 3,
      "test_code": "(is (= \"Lisp\" (tracks-on-tracks-on-tracks/first-language (quote (\"Lisp\" \"Clojure\")))))"
    },
    {
      "name": "list-remove-test",
      "status": "pass",
      "task_id": 4,
      "test_code": "(is (= (quote (\"Clojure\")) (tracks-on-tracks-on-tracks/remove-language (quote (\"Lisp\" \"Clojure\")))))"
    },
    {
      "name": "list-count-test",
      "status": "pass",
      "task_id": 5,
      "test_code": "(is (= 3 (tracks-on-tracks-on-tracks/count-languages (quote (\"JavaScript\" \"Java\" \"Clojure\")))))"
    },
    {
      "name": "learning-list-test",
      "status": "fail",
      "task_id": 6,
      "test_code": "(is (= 3 (tracks-on-tracks-on-tracks/learning-list)))",
      "message": "Expected (= 3 (tracks-on-tracks-on-tracks/learning-list)) but got (not (= 3 nil))"
    }
  ]
}
```

Note that this PR only adds the _support_ to the test runner for handling test id metadata, I have not added the metadata to any existing tests. The `exercism/clojure` repo will need a separate PR for that, and @BTowersCoding has created one already: exercism/clojure#434. However that PR would need to be updated to use the `^{:task 1}` style meta instead of `:task1` for the test runner to pick it up.

I also fixed a small bug that I found during testing, where passing tests with no assertions would be null in the output (there's only one example of this - in the strain exercise)

### CODE REVIEW

**Comment by miridius** [comment]
Since I started this PR from the branch used in #42, that PR needs to be finished first. Otherwise merging this one will merge them both.

**Comment by ErikSchierboom** [comment]
@miridius I'll look into this once #42 is merged.

**Comment by miridius** [comment]
Rebased this onto main now that #42 is merged

**Review by ErikSchierboom — APPROVED** [review]
LGTM!

**Comment by WarFox** [comment]
Can I offer any help needed here for getting this merged?

**Comment by BTowersCoding** [comment]
@WarFox I think this is ready to ship! In fact I think the only reason it hasn't been merged is that I wanted to do some further testing to ensure that it won't break anything, a concern which may or may not be justified...

If you'd like to help test it locally before we push it live, that would increase my confidence. There is a CI script over on the main repo which tests all the exercises, but it isn't a true integration test at the moment because it uses its own copy of the test runner. So what I would do is clone both repos, and modify the CI script to instead run the exercises against the new script contained in this branch.

**Comment by ErikSchierboom** [comment]
@BTowersCoding I think you're missing something. The `results.json` files don't contain the `task_id` field.

**Comment by BTowersCoding** [comment]
@ErikSchierboom you're right. I see that we're grabbing the metadata here and storing the `:task_id`:

```clojure
(defn report [{:keys [type] :as m}]
  (let [{:keys [name task]} (meta (first t/*testing-vars*))]
    {:name name
     :status type
     :task_id task
     :test_code (get-test-code name type)
     :message (get-message m)}))
```

...but then it isn't being included in the main function:

```clojure
(println (json/generate-string
          {:version 3
           :status (if (empty? @fails+errors) :pass :fail)
           :tests (for [test tests]
                    (->> (concat @fails+errors @passes [(default-report test)])
                         (filter #(= test (:name %)))
                         first
                         remove-nil-vals))}))
```

**Comment by ErikSchierboom** [comment]
> Is it okay that the key is not present if the exercise has no tasks? Or does it need to be there set to null or something?

Yep! That's great.

I've double checked and it _is_ working! Sorry about the confusion.

**Pull request merged**
